version: '2'

services:
  eureka:
    image: springcloud/eureka
    ports:
      - "8761:8761"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  pc:
    build: ./pc
    ports:
      - '8081:8081'
      - '5081:5081'
    depends_on:
      - eureka
      - mongo
      - config
    environment:
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://eureka:8761/eureka'
  po:
    build: ./po
    ports:
      - '8082:8082'
      - '5082:5082'
    links:
      - pc
    depends_on:
      - eureka
      - mongo
      - pc
      - config
    environment:
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://eureka:8761/eureka'
  config:
    build:
      context: .
      dockerfile: ./config/Dockerfile
    ports:
      - '8888:8888'
      - '5088:5088'
    depends_on:
      - eureka
    environment:
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://eureka:8761/eureka'
networks:
  default:
    driver: bridge
